### ISSUE TITLE
Why the QuadTreeRect struct properties not computed

### ISSUE THREAD

**Issue by sdcb** [leonidovia/UltimateQuadTree#1]
I think those MidX, MidY, Top, Bottom, Left, Right, _halfWidth, _halfHeight should be computed property such as: 

`public readonly double Top => X;`

This would save much memory and I think that may increase performance because of much less CPU cache invalidation.

**Comment by leonidovia** [comment]
**sdcb**, thanks for your message. Maybe you're right. I'll do a performance comparison for both versions.

**Comment by leonidovia** [comment]
I ran a performance test and I did not notice a significant difference. So I'll choose your version to save memory. Thank you for your advice.
