### ISSUE TITLE
IsIntersect is undefined

### ISSUE THREAD

**Issue by StevenGann** [leonidovia/UltimateQuadTree#2]
From the readme:

    var intersectingObjects = nearestObjects.Where(nearest => IsIntersect(nearest, myPolygon);

IsIntersect is not defined anywhere in this repository. Is this a typo?

**Comment by leonidovia** [comment]
Hello, Steven!
Please pay attention to the comment above:
// bool IsIntersect(Point[] obj1, Point[] obj2) is your function for checking intersections
This is your function that you write based on your goals.
